import Footer from '@/components/Footer'
import type { Metadata } from 'next'
import { Unbounded } from 'next/font/google'
import HeaderMain from '../components/HeaderMain'
import HeaderTop from '../components/HeaderTop'
import './globals.css'

const inter = Unbounded({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <HeaderTop /> */}
        <HeaderMain/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
